## ultrachat plugin file

name: UltraChat
version: 2013a
description: Chat formatting with in game editing and group support
author: prosicraft
website: http://minecraft.net
softdepend: [Vault]

main: com.prosicraft.ultrachat.UltraChat

commands:
    ultrachat:
        description: Universal UltraChat command
        usage: /<command> <format>
        permission: ultrachat.ultrachat
        aliases: [uc, chat]       